version: '2'
services:
  courier_server-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/courier_server/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=courier_server
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
