version: "3.8"

services:
  redis:
    image: "redis:alpine"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  db:
    image: 'postgres:13.1-alpine'
    container_name: pap_server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5543:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  admin:
    image: pap-admin
    build:
      context: .
      dockerfile: ./pap-admin/Dockerfile
    hostname: admin
    ports:
      - "8004:8004"
#    restart: on-failure
  courier:
    image: pap-courier
    build:
      context: .
      dockerfile: ./pap-courier/Dockerfile
    hostname: courier
    ports:
      - "8001:8001"
#    restart: on-failure
  customer:
    image: pap-customer
    build:
      context: .
      dockerfile: ./pap-customer/Dockerfile
    hostname: customer
    ports:
      - "8002:8002"
#    restart: on-failure
  restaurant:
    image: pap-restaurant
    build:
      context: .
      dockerfile: ./pap-restaurant/Dockerfile
    hostname: restaurant
    ports:
      - "8003:8003"