version: '2'
services:
  pap_admin-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/pap_admin/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pap_admin
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
